"""
##################################################
#
#           ** DO NOT EDIT THIS FILE **
#
##################################################
Version: 2023-04-08 (Python port of app/childapi/routes/example-jwt.js)

Demonstrates a route protected by JWT authentication.
"""


def apply(elmer, router, base_router=None):
    """Define a JWT protected route."""

    router.elmer = elmer.extend(
        router.elmer, {"security": elmer.resolve(elmer.app.config, "security.jwt")}
    )

    # curl -X POST http://localhost:3000/login/admin \
    #   -H 'Content-Type: application/json' \
    #   -d '{ "username":"cn", "password":"secret" }'
    # curl -X GET http://localhost:45000/example-jwt/secure \
    #   -H 'Authorization: JWT_GOES_HERE'
    @router.get("/secure")
    def _secure(request, response):
        response.status(200).json({"jwt": True})
