"""
##################################################
#
#           ** DO NOT EDIT THIS FILE **
#
##################################################
Version: 2025-03-27 (Python port of app/childapi/routes/example.js)

Boilerplate route module showing the four common patterns: path params,
multipart upload, spreadsheet upload, and a long-running delayed response.
"""

import json
import threading


def apply(elmer, router, base_router=None):
    """Define the example routes on the passed router.

    The router is created for you by _routes.py; you may also build your own
    via ``elmer.app.services.web.router()`` (just return it below).
    """

    # curl -X GET http://localhost:3000/childapi/byid/123 \
    #   -H 'Content-Type: application/json' -H 'Authorization: JWT_GOES_HERE'
    @router.get("/byid/:id")
    def _by_id(request, response):
        entry_id = elmer.type.int.mk(request.params.get("id"))
        response.status(200).json({"id": entry_id, "boilerplate": True})

    # curl -X POST http://localhost:3000/childapi/byfile \
    #   -F "upload=@/file/path/json.ext" > /file/path/output.json
    @router.post("/byfile")
    def _by_file(request, response):
        def on_complete(form_data):
            file_contents = json.loads(form_data.files.upload.get_content())
            # ..
            response.status(200).json({"ok": True, "received": file_contents})

        elmer.app.services.web.multipart_form(request, on_complete)

    # curl -X POST http://localhost:3000/childapi/xlsx \
    #   -F "upload=@/file/path/sheet.xlsx" > /file/path/output.json
    @router.post("/xlsx")
    def _xlsx(request, response):
        def on_complete(form_data):
            workbook = elmer.io.xlsx({
                "file": form_data.files.upload.get_content(),
                "options": {"type": "binary"},
            })
            rows = elmer.type.query(
                elmer.resolve(workbook, ["data", "Sheet1"]),
                {"status": lambda x: elmer.type.str.cmp(x, "active")},
            )
            # ..
            response.status(200).json({"ok": True, "rows": rows})

        elmer.app.services.web.multipart_form(
            request, on_complete, {"readFileSync": {"encoding": "binary"}}
        )

    # curl -X GET http://localhost:3000/childapi/delayed
    # curl -X GET http://localhost:3000/elmer/response/<id>
    @router.get("/delayed")
    def _delayed(request, response):
        data = {"neek": True, "arr": [1]}

        delayed_response = elmer.io.net.post(
            "http://localhost:3000/elmer/response",
            {"data": data},
            {"contentType": "application/json"},
        )
        response_id = elmer.resolve(delayed_response, "data.id")

        def tick():
            data["arr"].append(len(data["arr"]) + 1)
            elmer.io.net.post(
                "http://localhost:3000/elmer/response/" + str(response_id),
                {"data": data, "done": len(data["arr"]) == 10},
                {"contentType": "application/json"},
            )
            if len(data["arr"]) < 10:
                threading.Timer(5.0, tick).start()

        response.status(200).json({
            "ok": True,
            "id": response_id,
            "url": "http://localhost:3000/elmer/response/" + str(response_id),
        })

        threading.Timer(5.0, tick).start()

    # Return the router if it differs from the one passed in; return False to
    # tell Elmer not to register it at all.
    # return router
    # return False
