"""
##################################################
#
#           ** DO NOT EDIT THIS FILE **
#
##################################################
Version: 2023-04-08 (Python port of app/childapi/routes/example-basic.js)

Demonstrates a route protected by HTTP Basic authentication.
"""


def apply(elmer, router, base_router=None):
    """Define a Basic-auth protected route."""

    router.elmer = elmer.extend(
        router.elmer, {"security": elmer.resolve(elmer.app.config, "security.basic")}
    )

    # curl -X GET http://localhost:45000/example-basic/secure --user user1:pass1
    @router.get("/secure")
    def _secure(request, response):
        response.status(200).json({"basicAuth": True})
