"""
##################################################
#
#           ** DO NOT EDIT THIS FILE **
#
##################################################
Version: 2023-05-14 (Python port of _index.js)

Entry point: loads ishJS and its extensions, configures the app and HTTP
server, then starts listening and reports status to stdout.
"""

import json
import os
import sys

from flask_compress import Compress

# Ensure the project root is importable when run as a script.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# ==================================================
# Import the modules
# ==================================================
from app import _app, app_ex                                    # noqa: E402
from app._express import Server                                 # noqa: E402
from app.middleware import _requestid                           # noqa: E402
from app.routes import _routes                                  # noqa: E402

# Import ishJS + extensions
from libs.ish import (                                          # noqa: E402
    ish_io_csv, ish_io_net, ish_io_web, ish_oop_inherit,
    ish_oop_overload, ish_type_date_format, ish_type_enum, ish_type_ex,
)
from libs.ish.ish import core                                   # noqa: E402

_ROOT = os.path.dirname(os.path.abspath(__file__))

elmer = core()
ish_type_ex.apply(elmer)
ish_type_date_format.apply(elmer)
ish_io_net.apply(elmer)
ish_io_web.apply(elmer)
ish_io_csv.apply(elmer)
ish_oop_inherit.apply(elmer)
ish_oop_overload.apply(elmer)
ish_type_enum.apply(elmer)


def _load_config(name):
    """Read a JSON config file from app/config."""
    path = os.path.join(_ROOT, "app", "config", name + ".json")
    with open(path, "r", encoding="utf8") as handle:
        return json.load(handle)


def build():
    """Wire up the application and HTTP server, returning both."""
    http_server = Server(import_name="elmer")

    # ==================================================
    # Configure the elmer app
    # ==================================================
    _app.apply(elmer, http_server)
    app_ex.apply(elmer)

    # Pull in the config: base.json overlaid with the requested environment.
    args = elmer.app.config.args
    environment = (
        elmer.type.str.cmp(args[0] if args else None, ["dev", "prod"])
        and args[0].strip().lower()
    ) or "prod"

    elmer.app.config = elmer.extend(
        elmer.app.config,
        _load_config("base"),
        _load_config(environment),
    )

    # ==================================================
    # Configure the HTTP server
    # ==================================================
    # Support compressed bodies, unless the caller opts out per-request.
    compress = Compress()
    http_server.flask.config["COMPRESS_MIN_SIZE"] = 0
    compress.init_app(http_server.flask)

    @http_server.flask.after_request
    def _honour_no_compression(response):
        from flask import request as flask_request
        if flask_request.headers.get("x-no-compression"):
            response.headers.pop("Content-Encoding", None)
        return response

    # SECURITY (2026-08-06 audit): the app previously set no security
    # headers at all. CSP's script-src/style-src need 'unsafe-inline'
    # because the /www pages are zero-build — JSX is transpiled by
    # Babel from inline <script type="text/babel"> blocks at request
    # time, so there is no nonce/build step to attach a stricter policy
    # to. That is a real, accepted trade-off of the zero-build approach,
    # not an oversight; everything else in the policy is kept tight
    # (no wildcard sources, no framing, no unexpected origins).
    _CSP = "; ".join([
        "default-src 'self'",
        "script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com",
        "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
        "font-src 'self' https://fonts.gstatic.com",
        "img-src 'self' data:",
        "connect-src 'self'",
        "object-src 'none'",
        "base-uri 'none'",
        "frame-ancestors 'none'",
    ])

    @http_server.flask.after_request
    def _security_headers(response):
        response.headers.setdefault("Content-Security-Policy", _CSP)
        response.headers.setdefault("X-Content-Type-Options", "nosniff")
        response.headers.setdefault("X-Frame-Options", "DENY")
        response.headers.setdefault(
            "Referrer-Policy", "strict-origin-when-cross-origin")
        response.headers.setdefault(
            "Permissions-Policy",
            "camera=(), microphone=(), geolocation=(), payment=()")
        # Browsers only honour HSTS on responses actually received over
        # HTTPS, so it is safe to always send — harmless over plain HTTP
        # in local dev, effective once behind TLS (Vercel, or a reverse
        # proxy terminating TLS in front of Docker).
        response.headers.setdefault(
            "Strict-Transport-Security", "max-age=31536000; includeSubDomains")
        return response

    # Configure body size limits.
    #     NOTE: Unlike Express's body-parser, Flask parses bodies lazily, so
    #     proxied routes do not need to be excluded to keep their stream intact.
    if elmer.type.bool.mk(elmer.app.config.get("baseElmer"), False):
        elmer.app.services.web.config_body_parser("/elmer/*")
        elmer.app.services.web.config_body_parser("/example/*")
    else:
        elmer.app.services.web.config_body_parser()

    # Support X-Request-Id's (or X-Correlation-Id's / X-Trace-Id's)
    http_server.use(_requestid.apply(elmer))

    # Setup the /www route for static content
    # curl -X GET http://localhost:3000/www/ from /app/www
    http_server.static("/www", os.path.join(_ROOT, "app", "www"))
    http_server.static("/www/js/ish", os.path.join(_ROOT, "libs", "ish"))

    # Log each API request
    # http_server.use("/", _logapi.apply(elmer))

    # Install the fallback dispatcher that serves routers mounted at runtime
    # (child APIs registering themselves via /elmer/proxy).
    http_server.install_catchall()

    return elmer, http_server


_KNOWN_DEFAULT_SECRET_HASHES = {
    # SHA-256 fingerprints of the example secrets shipped in
    # app/config/base.json — compared, never the plaintext itself, so this
    # file doesn't become a second place carrying the actual secret value.
    "dd620c684874700dfdc07e56b425b3bec28e3af7b93e0055e01a477db2a317f5",  # jwtSecret
    "a8aa269dd4ef4f1450fbd4715c19ca095d1ce2084a15293a2bd8551d7f547ca0",  # localSecret
}
_KNOWN_WEAK_PASSWORDS = {"secret", "pass1", "pass2", "nonsecret", "unsecret"}


def _warn_if_unrotated_defaults():
    """Startup check (2026-08-06 security audit): nudge operators to
    rotate the example credentials shipped in app/config/base.json before
    any real deployment. Never blocks startup — this is advisory only,
    printed once to stderr where it won't be mistaken for API output.
    """
    import hashlib

    warnings = []

    jwt_secret = elmer.resolve(elmer.app.config, "security.jwt.salt.jwtSecret", "")
    if jwt_secret and hashlib.sha256(jwt_secret.encode()).hexdigest() in _KNOWN_DEFAULT_SECRET_HASHES:
        warnings.append(
            "security.jwt.salt.jwtSecret is still the example value shipped "
            "in app/config/base.json — every JWT this instance issues can be "
            "forged by anyone who has read the source. Set ELMER_JWT_SECRET."
        )

    for pool_path in ("security.basic.users", "security.jwt.admin",
                      "security.jwt.internal", "security.jwt.external"):
        for user in elmer.resolve(elmer.app.config, pool_path, []) or []:
            password = elmer.resolve(user, "p")
            if password in _KNOWN_WEAK_PASSWORDS:
                warnings.append(
                    "%s contains a user with the example password %r — "
                    "rotate it before any real deployment."
                    % (pool_path, password)
                )

    if not os.environ.get("ELMER_ADMIN_KEY") and not elmer.resolve(
            elmer.app.config, "elmer.adminKey"):
        warnings.append(
            "ELMER_ADMIN_KEY is unset — /elmer/proxy and /elmer/cache/* "
            "will refuse all requests (fail-closed) until it is set."
        )

    if warnings:
        rule = "!" * 70
        print(rule, file=sys.stderr)
        print("ELMER SECURITY WARNING — unrotated example credentials detected:",
             file=sys.stderr)
        for warning in warnings:
            print("  - " + warning, file=sys.stderr)
        print(rule, file=sys.stderr)


def on_listening():
    """Configure routes and report status once the server is up."""
    _warn_if_unrotated_defaults()

    elmer.app.status = elmer.extend(elmer.app.status, {
        "name": elmer.app.config.get("name"),
        "port": elmer.app.config.get("port"),
        "portLocal": elmer.app.config.get("portLocal"),
        "started": elmer.type.date.format(None, "YYYY/MM/DD hh:mm:ss"),
        "versions": {
            "ish": elmer.config.ish().ver,
            "app": elmer.app.version,
            "appEx": elmer.app.versionEx,
        },
    })

    # ==================================================
    # Configure the routes
    # ==================================================
    _routes.apply(elmer)

    # So long as this is not a base Elmer instance, set up the .api object
    # (including registering, if configured to do so).
    if not elmer.type.bool.mk(elmer.app.config.get("baseElmer"), False):
        elmer.app.status.api = {
            "heartbeat": elmer.resolve(
                elmer.app.services.web.api_up(elmer.app.config.name), "ok"
            ) is True,
            "registered": elmer.type.bool.mk(
                elmer.resolve(elmer.app.services.web.register(), "data.registered"),
                False,
            ),
            "dependencies": (
                elmer.resolve(
                    elmer.app.services.web.api_up(
                        elmer.app.config.get("dependencies")
                    ),
                    "ok",
                ) is True
                if elmer.type.arr.is_(elmer.app.config.get("dependencies"), True)
                else None
            ),
        }

    # Output a pretty-printed JSON representation of our status to stdout.
    print(json.dumps(elmer.app.status, indent=2, default=str))


def main():
    """Spin up the HTTP server.

    NOTE: Cannot bind to 127.0.0.1 — in Docker the server would then return
    "curl: (52) Empty reply from server".
    """
    _, http_server = build()
    http_server.listen(elmer.app.config.port, "0.0.0.0", on_listening)


if __name__ == "__main__":
    main()
