#!/bin/bash
##################################################
#
#           ** DO NOT EDIT THIS FILE **
#
##################################################
# Version: 2023-05-08 (Python port)
#
# Build/run wrapper. The only substantive change from the JavaScript original
# is the config-flattening step, which shelled out to `node -e` using ishJS;
# it now shells out to `python3 -c` instead. Docker orchestration, flag
# parsing and output are unchanged in behaviour.

NEWLINE=$'\n'
BLACKBOLD='\033[1;30m'  # See: https://stackoverflow.com/a/28938235
BLACKUNDER='\033[4;30m'
GREENBOLD='\033[1;32m'
BLUEBOLD='\033[1;34m'
REDBOLD='\033[1;31m'
RED='\033[0;31m'
RESET='\033[0m'         # No Color

# Loop through arguments and process them
#     See: https://pretzelhands.com/posts/command-line-flags/
for arg in "$@"
do
    case $arg in
        -p=*|--port=*)
        flagPort="${arg#*=}"
        shift # Remove --port= from processing
        ;;
        -e=*|--env=*)
        flagEnv="${arg#*=}"
        shift # Remove --env= from processing
        ;;
        -a|--all)
        flagSync=1
        flagRebuild=1
        flagLogs=1
        flagVars=1
        shift
        ;;
        -s|--sync)
        flagSync=1
        shift # Remove --sync from processing
        ;;
        -u|--update)
        flagUpdate=1
        shift # Remove --update from processing
        ;;
        -r|--rebuild)
        flagRebuild=1
        shift # Remove --rebuild from processing
        ;;
        -l|--logs)
        flagLogs=1
        shift # Remove --logs from processing
        ;;
        -v|--vars)
        flagVars=1
        shift # Remove --vars from processing
        ;;
        -n|--network)
        flagNetwork=1
        shift # Remove --network from processing
        ;;
        -t|--test)
        flagTest=1
        shift # Remove --test from processing
        ;;
        --config=*)
        flagConfigEnv="${arg#*=}"
        shift # Remove --config from processing
        ;;
        *)
        flagOthers+=("$1")
        shift # Remove generic argument from processing
        ;;
    esac
done


# Flatten base.json + the requested env.json into a dotted-key JSON file so the
# values can be exposed to this shell and to Docker. Returns the resolved env.
#     NOTE: the JS original did this with `node -e` and ish.type.obj.flatten.
flagEnv=$(python3 -c "
import json, sys

env = sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] in ('dev', 'prod') else 'dev'

def load(name):
    with open('./app/config/' + name + '.json', 'r', encoding='utf8') as handle:
        return json.load(handle)

def merge(target, source):
    for key, value in source.items():
        if isinstance(value, dict) and isinstance(target.get(key), dict):
            merge(target[key], value)
        else:
            target[key] = value
    return target

def flatten(obj, prefix=''):
    out = {}
    for key, value in obj.items():
        path = prefix + key
        if isinstance(value, dict):
            out.update(flatten(value, path + '.'))
        else:
            out[path] = value
    return out

config = flatten(merge(load('base'), load(env)))

with open('./app/config/config.json', 'w', encoding='utf8') as handle:
    json.dump(config, handle, indent=4)

print(env)
" "$flagEnv")

# Import the config.json variables into this script via export and into docker.env
vars=""
for keyval in  $(grep -E '\": [^\{]' ./app/config/config.json | sed -e 's/: /=/' -e "s/\(\,\)$//"); do
    eval export $keyval
    echo $keyval | sed 's/"//g' >> ./docker.env
    vars+="${keyval}${NEWLINE}"
done;
rm ./app/config/config.json



echo -e "${BLACKBOLD}######################################## ${RESET}"
echo -e "${BLACKBOLD}#${GREENBOLD} ${name} ${BLACKBOLD}=>${BLUEBOLD} ${flagEnv} ${RESET}"
echo -e "${BLACKBOLD}######################################## ${RESET}"



# Setup
if [ "$flagConfigEnv" = "base" ] || [ "$flagConfigEnv" = "child" ];
then
    if [ -d "./app/childapi" ];
    then
        echo "# Configuring Version: ${flagConfigEnv}"

        if [ "$flagConfigEnv" = "base" ];
        then
            rm -R ./app/childapi
        fi

        if [ "$flagConfigEnv" = "child" ];
        then
            rm -R ./app/middleware
            rm ./app/routes/elmer.py
            rm ./app/app_ex.py
            rm ./app/config/base.json

            mv ./app/childapi/app_ex.py ./app/app_ex.py
            mv ./app/childapi/config/base.json ./app/config/base.json
            mv ./app/childapi/routes/example.py ./app/routes/example.py
            rm -R ./app/childapi
        fi
    else
        echo "# Configuring Version: ERROR - This directory has already been configured!"
    fi
else
    :
fi


# Vars
if [[ $flagVars == 1 ]];
then
    echo "####################"
    echo "# Vars"
    echo "####################"
    echo "${vars}"
fi


# Sync
if [[ $flagSync == 1 ]];
then
    echo "####################"
    echo "# Syncing..."
    echo "####################"

    cp -R ../elmer/app/middleware/* ./app/middleware/
    cp ../elmer/app/routes/_routes.py ./app/routes/
    cp ../elmer/app/_app.py ./app/
    cp ../elmer/app/_express.py ./app/
    cp -R ../elmer/libs/* ./libs/
    cp ../elmer/_index.py .
    cp ../elmer/_tools.sh .

    flagUpdate=1
fi


# Update
if [[ $flagUpdate == 1 ]];
then
    echo "####################"
    echo "# Updating..."
    echo "####################"
    echo -e "# ${BLACKUNDER}NOTE:${RESET} Run in a virtualenv to avoid system-package conflicts."

    pip install --upgrade -r requirements.txt
fi


# Rebuild
if [[ $flagRebuild == 1 ]];
then
    echo "####################"
    echo "# Rebuilding..."
    echo "####################"

    # Docker
    docker network inspect api >/dev/null 2>&1 || docker network create api   # https://stackoverflow.com/a/53052379
    docker ps -a | grep $dockerBaseName/$name | awk '{ system("docker container stop " $1) }'
    docker build . -t $dockerBaseName/$name

    # Don't include dns definitions for $baseElmer
    if [[ $baseElmer == "true" ]];
    then
        docker run --net=$net --hostname $name.$hostname -p $portLocal:$port -d $dockerBaseName/$name
    else
        docker run --dns $dns1 --dns $dns2 --net=$net --hostname $name.$hostname -p $portLocal:$port -d $dockerBaseName/$name
    fi

    # Force the $flagLogs below and sleep to allow the logs to register
    flagLogs=1
    sleep 2
fi


# Log
if [[ $flagLogs == 1 ]];
then
    echo "####################"
    echo "# Logs"
    echo "####################"

    docker ps -a | grep $dockerBaseName/$name | awk '{ system("docker container logs " $1) }'
fi


# Network
if [[ $flagNetwork == 1 ]];
then
    echo "####################"
    echo "# Docker Network"
    echo "####################"

    docker network inspect api
fi


# Test
if [[ $flagTest == 1 ]];
then
    echo "Test successful; $flagOthers"
fi


# Remove the Docker environment file
sleep 1
rm ./docker.env
