"""
##################################################
#
#           ** DO NOT EDIT THIS FILE **
#
##################################################
Version: 2023-04-04a (Python port of app/middleware/_basicauth.js)

HTTP Basic authentication. Credentials are compared against the configured
user list; a small randomised delay is applied before responding.

Based on: https://stackoverflow.com/a/33905671/235704
"""

import base64
import hmac
import re
import time

from libs.ish.ish import Obj


def apply(elmer, config=None):
    """Return the Basic-auth middleware for the passed security config."""

    config = elmer.extend(
        Obj({
            # mode is inferred by use of this module; realm is defaulted below.
            "users": [Obj({
                "u": None,
                # Force a unique password so login fails if this default is used.
                "p": elmer.type.symbol.get(),
            })],
        }),
        elmer.resolve(elmer.app.config, "security.basic"),
        config,
    )

    config.users = elmer.type.arr.mk(config.get("users"), [config.get("users")])
    config.realm = elmer.type.str.mk(config.get("realm"), "api")

    def middleware(request, response, fn_continue):
        authorization = elmer.type.str.mk(request.headers.get("Authorization"))
        parts = authorization.split(" ")
        b64auth = parts[1] if len(parts) > 1 else ""

        try:
            decoded = base64.b64decode(b64auth).decode("utf8", errors="replace")
        except Exception:
            decoded = ""

        match = re.match(r"(.*?):(.*)", decoded)
        credentials = match.groups() if match else ()

        # To blunt crypto timing attacks, delay slightly based on process uptime.
        # Arguably security through obscurity, but random by definition.
        time.sleep(((time.monotonic() % 1) * 100) // 1 / 1000.0)

        user = None
        if len(credentials) == 2 and credentials[0] and credentials[1]:
            for candidate in config.users:
                if not elmer.type.obj.is_(candidate):
                    continue
                # Constant-time comparison for both halves of the credential.
                if (hmac.compare_digest(
                        str(credentials[0]), str(candidate.get("u") or ""))
                        and hmac.compare_digest(
                            str(credentials[1]), str(candidate.get("p") or ""))):
                    user = candidate
                    break

        if user:
            request.elmer = elmer.type.obj.mk(request.elmer, Obj())
            request.elmer.user = user
            fn_continue()
        else:
            response.set("WWW-Authenticate", 'Basic realm="%s"' % config.realm)
            response.status(401).json({
                "method": "BasicAuth",
                "error": "Authentication required.",
            })

    return middleware
