"""
##################################################
#
#           ** DO NOT EDIT THIS FILE **
#
##################################################
Version: 2023-05-18 (Python port of app/middleware/_cache.js)

Records every response against its trace id in ``elmer.app.cache``, so that
the /elmer/cache/* routes can later retrieve or clear it.
"""

from libs.ish.ish import Obj


def apply(elmer, route):
    """Return the caching middleware for the given mount point."""
    if not elmer.type.obj.is_(elmer.resolve(elmer.app, "cache")):
        elmer.app.cache = Obj()

    def middleware(request, response, fn_continue):

        response.error_code = 0

        def on_finish():
            url = request.url

            data = Obj({
                "trace": request.trace,
                "route": route,
                "subroute": "",
                "url": url,
                "status": response.status_code,
                "error": response.error_code,
                "data": response.body,
            })

            request.trace["completed"] = elmer.type.date.timestamp()
            request.trace["runtime"] = elmer.type.date.diff(
                request.trace.get("started"), request.trace["completed"], "s"
            )

            # Trim any querystring or fragment off the end of the URL.
            cut = None
            if "?" in url:
                cut = url.index("?")
            elif "#" in url:
                cut = url.index("#")

            start = url.find(route) + len(route)
            data.subroute = url[start:cut] if cut is not None else url[start:]

            # Ensure the trace-id bucket exists, then append.
            if request.trace["id"] not in elmer.app.cache:
                elmer.app.cache[request.trace["id"]] = []
            elmer.app.cache[request.trace["id"]].append(data)

        response.on("finish", on_finish)
        fn_continue()

    return middleware
