"""
##################################################
#
#           ** DO NOT EDIT THIS FILE **
#
##################################################
Version: 2023-04-04b (Python port of app/middleware/_jwt.js)

Registers ``elmer.app.services.security.jwt`` (login router, sign, verify) and
returns the middleware that guards protected routes by validating the token
supplied in the Authorization header or the ``auth`` cookie.
"""

import hmac
import re
import time
from datetime import datetime, timedelta, timezone

import jwt as _jwt

from libs.ish.ish import Obj


def _expires_in_seconds(value, default=3600):
    """Parse an expiry such as "1 hours" / "8 hours" / "30m" into seconds."""
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return int(value)
    match = re.match(r"^\s*(\d+)\s*([a-zA-Z]*)\s*$", str(value or ""))
    if not match:
        return default
    amount = int(match.group(1))
    unit = (match.group(2) or "s").lower()
    multipliers = {
        "": 1, "s": 1, "sec": 1, "secs": 1, "second": 1, "seconds": 1,
        "m": 60, "min": 60, "mins": 60, "minute": 60, "minutes": 60,
        "h": 3600, "hour": 3600, "hours": 3600,
        "d": 86400, "day": 86400, "days": 86400,
    }
    return amount * multipliers.get(unit, 1)


def apply(elmer, security_config=None):
    """Configure the JWT service and return the guarding middleware."""

    # Process the passed config into an object with defaults applied.
    security_config = elmer.extend(
        Obj({
            # mode ("jwt") is inferred by use of this module.
            "salt": Obj({
                "jwtSecret": "",
                "localSecret": "",
                "public": Obj({"admin": "", "internal": "", "external": ""}),
            }),
            "admin": [],
            "internal": [],
            "external": [],
        }),
        elmer.resolve(elmer.app.config, "security.jwt"),
        security_config,
    )

    # ----------------------------------------------
    # elmer.app.services.security.jwt
    # ----------------------------------------------
    def default_error():
        return Obj({
            "method": "jwt",
            "error": "Incorrect username/password combination.",
        })

    def verify(token):
        """Verify a token against the configured secret, returning its claims."""
        secret = elmer.resolve(elmer.app.config, "security.jwt.salt.jwtSecret", "")
        return _jwt.decode(token, secret, algorithms=["HS256"])

    def login(request, response, mode):
        """Authenticate a username/password pair and issue a signed token."""
        body = elmer.type.obj.mk(request.body, None)
        return_val = default_error()

        # To blunt crypto timing attacks, delay slightly based on process uptime.
        # Arguably security through obscurity, but random by definition.
        time.sleep(((time.monotonic() % 1) * 100) // 1 / 1000.0)

        user_types = elmer.app.enums.userTypes
        jwt_config = None

        if mode == user_types.admin:
            jwt_config = Obj({
                "salt": elmer.resolve(security_config, "salt.public.admin"),
                "users": security_config.get("admin"),
                "expiresIn": "1 hours",
            })
        elif mode == user_types.internal:
            jwt_config = Obj({
                "salt": elmer.resolve(security_config, "salt.public.internal"),
                "users": security_config.get("internal"),
                "expiresIn": "8 hours",
            })
        elif mode == user_types.external:
            jwt_config = Obj({
                "salt": elmer.resolve(security_config, "salt.public.external"),
                "users": security_config.get("external"),
                "expiresIn": "8 hours",
            })

        secret = elmer.resolve(security_config, "salt.jwtSecret", "")
        user = None

        if (body and jwt_config
                and elmer.type.arr.is_(jwt_config.users, True)
                and elmer.type.str.is_(secret, True)):

            for candidate in jwt_config.users:
                if not elmer.type.obj.is_(candidate):
                    continue
                if (hmac.compare_digest(
                        str(body.get("username") or ""),
                        str(candidate.get("u") or ""))
                        and hmac.compare_digest(
                            str(body.get("password") or ""),
                            str(candidate.get("p") or ""))):
                    user = elmer.extend(Obj(), candidate)
                    break

            if user:
                expires = _expires_in_seconds(jwt_config.expiresIn)
                token = _jwt.encode(
                    {
                        "username": user.get("u"),
                        "role": mode,
                        "iat": datetime.now(timezone.utc),
                        "exp": datetime.now(timezone.utc) + timedelta(seconds=expires),
                    },
                    secret,
                    algorithm="HS256",
                )
                # Never echo the password back to the caller.
                user.pop("p", None)
                return_val = elmer.extend(user, Obj({"jwt": token}))

        response.status(200 if user else 401).json(return_val)

    def login_router():
        """Build the /login router (admin, internal, external and verify)."""
        router = elmer.app.services.web.router()

        # Ensure the JWT service is configured before the routes are used.
        apply(elmer, None)

        user_types = elmer.app.enums.userTypes

        # curl -X POST http://localhost:45000/login/admin \
        #   -H 'Content-Type: application/json' \
        #   -d '{ "username":"cn", "password":"secret" }'
        @router.post("/admin")
        def _login_admin(request, response):
            elmer.app.services.security.jwt.login(request, response, user_types.admin)

        @router.post("/internal")
        def _login_internal(request, response):
            elmer.app.services.security.jwt.login(
                request, response, user_types.internal
            )

        @router.post("/")
        def _login_external(request, response):
            elmer.app.services.security.jwt.login(
                request, response, user_types.external
            )

        # curl -X POST http://localhost:45000/login/verify/admin \
        #   -H 'Content-Type: application/json' -d '{ "jwt":"JWT_GOES_HERE" }'
        @router.post("/verify/:mode")
        def _login_verify(request, response):
            try:
                claims = elmer.app.services.security.jwt.verify(
                    elmer.resolve(request.body, "jwt")
                )
                response.status(200).json(claims)
            except _jwt.PyJWTError as error:
                response.status(401).json({"method": "jwt", "error": str(error)})

        @router.all("*")
        def _login_catchall(request, response, **_kwargs):
            response.status(401).json(
                elmer.app.services.security.jwt.default_error()
            )

        return router

    elmer.app.services.security.jwt = Obj({
        "default_error": default_error,
        "defaultError": default_error,
        "verify": verify,
        "login": login,
        "login_router": login_router,
        "loginRouter": login_router,
    })

    # ----------------------------------------------
    # The guarding middleware
    # ----------------------------------------------
    def middleware(request, response, fn_continue):
        auth = (elmer.resolve(request.headers, "Authorization")
                or elmer.resolve(request.headers, "authorization")
                or elmer.resolve(request.cookies, "auth"))

        # Reserved for trusted loopback callers; disabled as in the original.
        is_local_request = False

        if elmer.type.str.is_(auth, True):
            if is_local_request:
                if auth == elmer.resolve(security_config, "salt.localSecret"):
                    request.user = Obj({"local": True})
                else:
                    response.status(401).json({
                        "method": "jwt",
                        "error": "Authentication required.",
                    })
                    return
            else:
                try:
                    secret = elmer.resolve(security_config, "salt.jwtSecret", "")
                    request.user = _jwt.decode(auth, secret, algorithms=["HS256"])
                except _jwt.PyJWTError:
                    response.status(401).json({
                        "method": "jwt",
                        "error": "Authentication required.",
                    })
                    return
        else:
            response.status(401).json({
                "method": "jwt",
                "error": "Authorization cannot be empty.",
            })
            return

        fn_continue()

    return middleware
