"""
##################################################
#
#           ** DO NOT EDIT THIS FILE **
#
##################################################
Version: 2023-04-04 (Python port of app/middleware/_logapi.js)

Captures each response's status code, JSON body and error code, then hands
them to ``elmer.app.log.api`` once the response finishes.

The JS original monkeypatches ``res.json``/``res.status``; here the Response
object already records both, so the middleware simply reads them back on the
'finish' event.
"""


def apply(elmer):
    """Return the middleware function."""

    def middleware(request, response, fn_continue):

        # Expose the $errorCode interface used by route handlers.
        response.error_code = 0

        def on_finish():
            elmer.app.log.api(
                {
                    "status": response.status_code,
                    "json": response.body,
                    "error": response.error_code,
                },
                request,
            )

        response.on("finish", on_finish)
        fn_continue()

    return middleware
