"""
##################################################
#
#           ** DO NOT EDIT THIS FILE **
#
##################################################
Version: 2023-07-04 (Python port of app/middleware/_requestid.js)

Attaches a correlation/trace identifier to every request, honouring an
inbound X-Request-Id (or X-Correlation-Id / X-Trace-Id) when one is supplied
and minting a UUID when one is not.

See: https://hilton.org.uk/blog/microservices-correlation-id
"""

import json

from libs.ish.ish import Obj


def apply(elmer):
    """Return the middleware function."""

    def middleware(request, response, fn_continue):
        headers = request.headers

        trace_source = elmer.type.str.mk(
            elmer.type.obj.get(headers, "X-Request-Id")
            or elmer.type.obj.get(headers, "X-Correlation-Id")
            or elmer.type.obj.get(headers, "X-Trace-Id")
            or elmer.type.obj.get(
                elmer.io.web.queryString.parse(request.url), "RequestId"
            )
            or elmer.type.obj.get(request.body, "RequestId")
        )

        # The inbound value may itself be a serialised trace object.
        trace = elmer.type.obj.mk(trace_source, None) or Obj({"id": trace_source})

        id_present = elmer.type.is_.truthy(trace.get("id"))
        trace_id = trace["id"] if id_present else elmer.type.uuid()

        request.trace = elmer.extend(
            Obj({
                "id": trace_id,
                "parentid": None,
                "generatedid": id_present,
                "sync": True,
                "started": elmer.type.date.timestamp(),
                "when": elmer.type.date.format(
                    elmer.type.date.utc_to_local_offset(), "YYYY-MM-DD HH:mm:ss"
                ),
                "completed": None,
                "runtime": 0,
            }),
            trace,
            # Applied last so the resolved id always wins: when no usable id
            # arrives on the request, `trace` carries an empty string that
            # would otherwise clobber the freshly generated UUID and leave
            # the response uncacheable.
            Obj({"id": trace_id}),
        )

        response.set("X-Request-Id", json.dumps(dict(request.trace), default=str))
        fn_continue()

    return middleware
