"""
##################################################
#
#           ** DO NOT EDIT THIS FILE **
#
##################################################
Python port of ish.js core (libs/ish/ish.js).

ishJS is a "type-safe-ish" utility library. Its central idiom is the pairing of
``.is()`` interrogators with ``.mk()`` coercers:

    ish.type.str.is(x)        -> bool   "is x a string?"
    ish.type.str.is(x, True)  -> bool   "is x a *non-empty* string?"
    ish.type.str.mk(x, "d")   -> str    "give me x as a string, else 'd'"

Because the original is JavaScript, several coercions are deliberately loose
(e.g. ``bool.mk("true")`` is True). Those semantics are preserved here so the
ported application behaves the same way.

Original ishJS/Elmer: Copyright (c) 2021-2023 Nick Campbell, MIT licensed.
See the accompanying LICENSE file.
"""

import json
import math
import re
import time
import uuid as _uuid
from datetime import datetime, timezone

VERSION = "0.12.2025-03-27-py"


# ==================================================
# Internal helpers
# ==================================================
class Obj(dict):
    """A dict that also supports attribute access.

    JavaScript makes no distinction between ``o.key`` and ``o["key"]``. The
    ported code leans on that constantly (``$elmer.app.config.port``), so this
    small subclass lets the Python port read like the original without
    sprinkling ``["..."]`` everywhere.
    """

    def __getattr__(self, name):
        try:
            return self[name]
        except KeyError:
            raise AttributeError(name)

    def __setattr__(self, name, value):
        self[name] = value

    def __delattr__(self, name):
        try:
            del self[name]
        except KeyError:
            raise AttributeError(name)


def _wrap(value):
    """Recursively wrap plain dicts as Obj so attribute access works throughout."""
    if isinstance(value, Obj):
        return value
    if isinstance(value, dict):
        return Obj({k: _wrap(v) for k, v in value.items()})
    if isinstance(value, list):
        return [_wrap(v) for v in value]
    return value


def _is_plain_obj(value):
    """A JS "object" for our purposes: a mapping (but not a list/str)."""
    return isinstance(value, dict)


# ==================================================
# ish.extend
# ==================================================
def extend(target, *sources):
    """Deep-merge each source into target, returning target (jQuery.extend-alike).

    Mirrors ``ish.extend``: later sources win, nested objects merge rather than
    replace, and a value of ``None``/undefined does not clobber an existing one.
    """
    if target is None:
        target = Obj()
    if not _is_plain_obj(target):
        # Callables get attributes attached rather than merged, matching the
        # JS pattern of extending a function with properties (see web.router).
        for source in sources:
            if _is_plain_obj(source):
                for key, value in source.items():
                    setattr(target, key, _wrap(value))
        return target

    target = _wrap(target)
    for source in sources:
        if not _is_plain_obj(source):
            continue
        for key, value in source.items():
            if _is_plain_obj(value) and _is_plain_obj(target.get(key)):
                extend(target[key], value)
            elif value is not None:
                target[key] = _wrap(value)
            elif key not in target:
                target[key] = None
    return target


# ==================================================
# ish.resolve
# ==================================================
def resolve(source, path=None, default=None):
    """Safely walk a dotted/list path, returning ``default`` on any miss.

    ``resolve(o, "security.jwt.salt")`` and ``resolve(o, ["cache", a, b])`` are
    both supported, exactly as in ish.js.
    """
    if path is None:
        return source if source is not None else default

    if isinstance(path, str):
        keys = [k for k in path.split(".") if k != ""]
    elif isinstance(path, (list, tuple)):
        keys = list(path)
    else:
        keys = [path]

    current = source
    for key in keys:
        if current is None:
            return default
        try:
            if _is_plain_obj(current):
                if key not in current:
                    return default
                current = current[key]
            elif isinstance(current, (list, tuple)):
                current = current[int(key)]
            else:
                current = getattr(current, str(key))
        except (KeyError, IndexError, AttributeError, TypeError, ValueError):
            return default
    return current if current is not None else default


# ==================================================
# ish.type.*
# ==================================================
class _Is:
    """ish.type.is.* — general interrogators."""

    @staticmethod
    def truthy(x):
        """JS truthiness: 0, "", None, False and NaN are falsy; all else truthy."""
        if x is None or x is False or x == 0 or x == "":
            return False
        if isinstance(x, float) and math.isnan(x):
            return False
        return True

    @staticmethod
    def val(x, types):
        types = types if isinstance(types, (list, tuple)) else [types]
        return isinstance(x, tuple(types))


class _Str:
    """ish.type.str.*"""

    @staticmethod
    def is_(x, disallow_null_string=False):
        if not isinstance(x, str):
            return False
        return bool(x) if disallow_null_string else True

    @staticmethod
    def mk(x, default=""):
        if isinstance(x, str):
            return x
        if x is None:
            return default
        if isinstance(x, bool):
            return "true" if x else "false"
        if isinstance(x, (int, float)):
            # Render whole floats without the trailing ".0", as JS would.
            if isinstance(x, float) and x.is_integer():
                return str(int(x))
            return str(x)
        if isinstance(x, (dict, list)):
            try:
                return json.dumps(x)
            except (TypeError, ValueError):
                return default
        try:
            return str(x)
        except Exception:
            return default

    @staticmethod
    def cmp(x, y, case_insensitive=True):
        """Compare a string against a value or list of values.

        Returns True when x matches (any of) y. Used throughout Elmer for
        things like ``str.cmp(mode, ["basic", "jwt"])``.
        """
        if not isinstance(x, str):
            return False
        candidates = y if isinstance(y, (list, tuple)) else [y]
        left = x.strip().lower() if case_insensitive else x.strip()
        for candidate in candidates:
            if not isinstance(candidate, str):
                continue
            right = candidate.strip().lower() if case_insensitive else candidate.strip()
            if left == right:
                return True
        return False


class _Int:
    """ish.type.int.*"""

    @staticmethod
    def is_(x):
        return isinstance(x, int) and not isinstance(x, bool)

    @staticmethod
    def mk(x, default=0):
        if isinstance(x, bool):
            return 1 if x else 0
        if isinstance(x, int):
            return x
        if isinstance(x, float):
            if math.isnan(x) or math.isinf(x):
                return default
            return int(x)
        if isinstance(x, str):
            try:
                return int(float(x.strip()))
            except (TypeError, ValueError):
                return default
        return default


class _Float:
    """ish.type.float.*"""

    @staticmethod
    def is_(x):
        return isinstance(x, float)

    @staticmethod
    def mk(x, default=0.0):
        if isinstance(x, bool):
            return 1.0 if x else 0.0
        if isinstance(x, (int, float)):
            return float(x)
        if isinstance(x, str):
            try:
                return float(x.strip())
            except (TypeError, ValueError):
                return default
        return default


class _Bool:
    """ish.type.bool.*"""

    _TRUE = ("true", "1", "yes", "y", "on")
    _FALSE = ("false", "0", "no", "n", "off", "")

    @staticmethod
    def is_(x):
        return isinstance(x, bool)

    @classmethod
    def mk(cls, x, default=False):
        if isinstance(x, bool):
            return x
        if isinstance(x, (int, float)) and not isinstance(x, bool):
            return x != 0
        if isinstance(x, str):
            lowered = x.strip().lower()
            if lowered in cls._TRUE:
                return True
            if lowered in cls._FALSE:
                return False
        return default


class _Arr:
    """ish.type.arr.*"""

    @staticmethod
    def is_(x, disallow_empty=False):
        if not isinstance(x, (list, tuple)):
            return False
        return bool(x) if disallow_empty else True

    @staticmethod
    def mk(x, default=None):
        if isinstance(x, list):
            return x
        if isinstance(x, tuple):
            return list(x)
        if default is not None:
            return default
        return []


class _ObjType:
    """ish.type.obj.*"""

    @staticmethod
    def is_(x, disallow_empty=False):
        if not _is_plain_obj(x):
            return False
        return bool(x) if disallow_empty else True

    @staticmethod
    def mk(x, default=None):
        """Coerce to an object, JSON-parsing strings where possible."""
        if _is_plain_obj(x):
            return _wrap(x)
        if isinstance(x, str) and x.strip():
            try:
                parsed = json.loads(x)
                if _is_plain_obj(parsed):
                    return _wrap(parsed)
            except (TypeError, ValueError):
                pass
        if default is not None:
            return _wrap(default)
        return None if default is None and default is not Ellipsis else Obj()

    @staticmethod
    def has(source, key):
        return _is_plain_obj(source) and key in source

    @staticmethod
    def get(source, key, return_all_matching=False):
        """Fetch a key, supporting exact, callable, regex and case-insensitive lookup.

        The case-insensitive fallback matters because ish.js is used against
        HTTP headers, where casing is not guaranteed.
        """
        if not _is_plain_obj(source):
            return None

        matches = {} if return_all_matching else None

        if callable(key) and not isinstance(key, (str, bytes)):
            test = key
        elif isinstance(key, re.Pattern):
            test = lambda candidate: bool(key.search(candidate))
        else:
            wanted = str(key)
            if wanted in source:
                return source[wanted]
            lowered = wanted.lower()
            test = lambda candidate: candidate.lower() == lowered

        for candidate_key, value in source.items():
            if test(str(candidate_key)):
                if return_all_matching:
                    matches[candidate_key] = value
                else:
                    return value
        return matches


class _Fn:
    """ish.type.fn.*"""

    @staticmethod
    def is_(x):
        return callable(x)

    @staticmethod
    def mk(x, default=None):
        if callable(x):
            return x
        if callable(default):
            return default
        return lambda *args, **kwargs: None

    @staticmethod
    def run(fn, options=None):
        """Invoke fn with optional args, swallowing nothing but a bad callable."""
        if not callable(fn):
            return None
        options = options or {}
        args = options.get("args", []) or []
        return fn(*args)

    @staticmethod
    def once(fn):
        """Wrap fn so it only ever executes once, re-returning the first result.

        Elmer relies on this because formidable's 'end' event can fire twice.
        """
        state = {"called": False, "value": None}

        def wrapper(*args, **kwargs):
            if not state["called"]:
                state["called"] = True
                state["value"] = fn(*args, **kwargs) if callable(fn) else None
            return state["value"]

        return wrapper

    @staticmethod
    def noop(*args, **kwargs):
        return None


class _Symbol:
    """ish.type.symbol.* — unique, unguessable sentinel values."""

    @staticmethod
    def get(description=""):
        return "@@ish.symbol:%s:%s" % (description, _uuid.uuid4())


class _Date:
    """ish.type.date.* (core + the type-ex/date-format extensions)."""

    @staticmethod
    def is_(x, allow_string=True):
        if isinstance(x, datetime):
            return True
        if allow_string and isinstance(x, str):
            return _Date.mk(x, None) is not None
        return False

    @staticmethod
    def mk(x=None, default=Ellipsis):
        """Coerce to a datetime. Accepts datetime, epoch ms/s, and ISO-ish strings."""
        fallback = datetime.now() if default is Ellipsis else default

        if x is None:
            return datetime.now() if default is Ellipsis else fallback
        if isinstance(x, datetime):
            return x
        if isinstance(x, bool):
            return fallback
        if isinstance(x, (int, float)):
            # JS timestamps are milliseconds; anything huge is treated as such.
            seconds = x / 1000.0 if abs(x) > 3_000_000_000 else float(x)
            try:
                return datetime.fromtimestamp(seconds)
            except (OverflowError, OSError, ValueError):
                return fallback
        if isinstance(x, str):
            candidate = x.strip()
            if not candidate:
                return fallback
            try:
                return datetime.fromisoformat(candidate.replace("Z", "+00:00"))
            except ValueError:
                pass
            for fmt in (
                "%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S",
                "%Y-%m-%d", "%Y/%m/%d",
                "%a, %d %b %Y %H:%M:%S %Z", "%m/%d/%Y",
            ):
                try:
                    return datetime.strptime(candidate, fmt)
                except ValueError:
                    continue
            if candidate.lstrip("-").isdigit():
                return _Date.mk(int(candidate), default)
        return fallback

    @staticmethod
    def timestamp(whole_seconds=False):
        """Epoch milliseconds, matching JS ``Date.now()``."""
        value = time.time() * 1000.0
        return round(value) if whole_seconds else value

    @staticmethod
    def utc_to_local_offset(x=None):
        """Reinterpret a date's UTC components as local wall-clock components."""
        source = _Date.mk(x)
        utc = source.astimezone(timezone.utc) if source.tzinfo else source
        return datetime(utc.year, utc.month, utc.day, utc.hour, utc.minute, utc.second)

    @staticmethod
    def format(x=None, fmt="YYYY-MM-DD HH:mm:ss"):
        """Format using ish/moment-style tokens (YYYY, MM, DD, HH, hh, mm, ss...)."""
        d = _Date.mk(x)
        hour12 = d.hour % 12 or 12
        tokens = [
            ("YYYY", "%04d" % d.year),
            ("YY", "%02d" % (d.year % 100)),
            ("MMMM", d.strftime("%B")),
            ("MMM", d.strftime("%b")),
            ("MM", "%02d" % d.month),
            ("DDDD", d.strftime("%A")),
            ("DDD", d.strftime("%a")),
            ("DD", "%02d" % d.day),
            ("HH", "%02d" % d.hour),
            ("hh", "%02d" % hour12),
            ("mm", "%02d" % d.minute),
            ("ss", "%02d" % d.second),
            ("SSS", "%03d" % (d.microsecond // 1000)),
            ("A", "AM" if d.hour < 12 else "PM"),
            ("a", "am" if d.hour < 12 else "pm"),
        ]
        # Longest-token-first replacement into a placeholder buffer, so that
        # already-substituted output can never be re-matched.
        result, index = [], 0
        text = _Str.mk(fmt)
        while index < len(text):
            for token, value in tokens:
                if text.startswith(token, index):
                    result.append(value)
                    index += len(token)
                    break
            else:
                result.append(text[index])
                index += 1
        return "".join(result)

    @staticmethod
    def cmp(x, y):
        """-1 / 0 / 1 comparison of two dates."""
        dx, dy = _Date.mk(x, None), _Date.mk(y, None)
        if dx is None or dy is None:
            return 0
        if dx < dy:
            return -1
        return 1 if dx > dy else 0

    @staticmethod
    def diff(x, y, unit="ms"):
        """Difference between two dates in the requested unit."""
        dx, dy = _Date.mk(x, None), _Date.mk(y, None)
        if dx is None or dy is None:
            return 0
        delta_ms = abs((dy - dx).total_seconds() * 1000.0)
        unit = _Str.mk(unit, "ms").strip().lower()
        divisors = {
            "ms": 1.0, "s": 1000.0, "m": 60000.0,
            "h": 3600000.0, "d": 86400000.0, "y": 31536000000.0,
        }
        return delta_ms / divisors.get(unit, 1.0)

    @staticmethod
    def ydhms(x, y=None):
        """Human "1y 2d 3h 4m 5s" elapsed-time string between two dates."""
        dx = _Date.mk(x)
        dy = _Date.mk(y) if y is not None else datetime.now()

        delta = abs((dy - dx).total_seconds())
        out = ""

        days = int(delta // 86400)
        delta -= days * 86400
        if days > 0:
            if days > 364:
                out += "%dy " % (days // 365)
            out += "%dd " % (days % 365)

        hours = int(delta // 3600)
        delta -= hours * 3600
        if hours > 0 or out:
            out += "%dh " % hours

        minutes = int(delta // 60)
        delta -= minutes * 60
        if minutes > 0 or out:
            out += "%dm " % minutes

        out += "%ds" % int(delta)
        return out.strip()


# --------------------------------------------------
# ish.type.query
# --------------------------------------------------
def _matches_criteria(entry, criteria, case_insensitive=False):
    """Recursively test one entry against a (possibly nested) criteria object."""
    if not _is_plain_obj(criteria):
        return False

    for key, expected in criteria.items():
        actual = entry.get(key) if _is_plain_obj(entry) else resolve(entry, key)

        if callable(expected) and not isinstance(expected, (str, bytes)):
            if not expected(actual):
                return False
        elif _is_plain_obj(expected):
            if not _matches_criteria(actual, expected, case_insensitive):
                return False
        elif case_insensitive and isinstance(expected, str) and isinstance(actual, str):
            if expected.strip().lower() != actual.strip().lower():
                return False
        elif actual != expected:
            return False
    return True


def query(source, criteria, options=None):
    """Search a list (or dict-of-lists) for entries matching criteria.

    Options mirror ish.js: ``firstEntryOnly`` returns a single entry (or None)
    rather than a list, and ``caseInsensitive`` relaxes string comparison.
    """
    options = options or {}
    first_only = bool(options.get("firstEntryOnly", False))
    case_insensitive = bool(options.get("caseInsensitive", False))

    matches = []

    def consider(entry):
        if _matches_criteria(entry, criteria, case_insensitive):
            matches.append(entry)

    if isinstance(source, (list, tuple)):
        for entry in source:
            consider(entry)
    elif _is_plain_obj(source):
        for value in source.values():
            if isinstance(value, (list, tuple)):
                for entry in value:
                    consider(entry)
            else:
                consider(value)

    if first_only:
        return matches[0] if matches else None
    return matches


def uuid():
    """ish.type.uuid — RFC4122 v4 identifier."""
    return str(_uuid.uuid4())


# ==================================================
# Assemble the namespace
# ==================================================
class _Type:
    is_ = _Is
    str = _Str
    int = _Int
    float = _Float
    bool = _Bool
    arr = _Arr
    obj = _ObjType
    fn = _Fn
    date = _Date
    symbol = _Symbol
    query = staticmethod(query)
    uuid = staticmethod(uuid)


class Ish:
    """The ``$elmer`` root object: a namespace that modules extend at runtime."""

    def __init__(self):
        self.type = _Type()
        self.extend = extend
        self.resolve = resolve
        self.io = Obj()
        self.config = Obj({"ish": lambda: Obj({"ver": VERSION})})
        # Populated by app/_app.py and app/app_ex.py
        self.app = Obj()

    # Convenience passthroughs so `ish.query(...)` reads naturally.
    def query(self, source, criteria, options=None):
        return query(source, criteria, options)


def core():
    """Factory mirroring ``require('./libs/ish/ish.js')``."""
    return Ish()
