"""
##################################################
#
#           ** DO NOT EDIT THIS FILE **
#
##################################################
Version: 0.2.2025-03-27 (Python port of app/_app.js)

Builds the ``$elmer.app`` namespace: configuration, the web service layer
(router registry, multipart handling, API heartbeat checks) and the filesystem
service layer (zip generation, recursive route loading).
"""

import importlib.util
import io
import os
import socket
import sys
import zipfile

from libs.ish.ish import Obj

from ._express import Router

APP_VERSION = "0.2.2025-03-27"

_HERE = os.path.dirname(os.path.abspath(__file__))


# ==================================================
# Helpers
# ==================================================
def _local_ip():
    """Best-effort local IP address (the `ip` npm package equivalent)."""
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        # No packets are actually sent; this just selects the outbound interface.
        sock.connect(("8.8.8.8", 80))
        return sock.getsockname()[0]
    except OSError:
        return "127.0.0.1"
    finally:
        sock.close()


def _load_module_from_path(path):
    """Import a Python file by absolute path, mirroring Node's require(path)."""
    module_name = "elmer_route_" + os.path.splitext(os.path.basename(path))[0]
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise ImportError("Unable to load module at %s" % path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


# ==================================================
# module.exports
# ==================================================
def apply(elmer, server):
    """Populate ``elmer.app``. Equivalent to ``require('./app/_app.js')(...)``."""

    # ----------------------------------------------
    # services.web.multipartForm
    # ----------------------------------------------
    def multipart_form(request, on_complete, options=None):
        """Collect a multipart request into fields/files (formidable equivalent).

        Each file entry exposes ``get_content()``, honouring the configured
        encoding, so callers can read the upload without touching disk paths.
        """
        options = elmer.extend(
            Obj({
                "fileSizeMb": elmer.resolve(elmer.app.config, "uploadLimitMb", 500),
                "multiples": True,
                "uploadDir": os.path.join(_HERE, "uploads"),
                "readFileSync": Obj({"encoding": "utf8"}),
            }),
            options,
        )

        form_data = Obj({"fields": Obj(), "files": Obj()})
        encoding = elmer.resolve(options, "readFileSync.encoding", "utf8")

        # -- fields --
        for field, value in request.form.items(multi=True):
            if elmer.type.obj.has(form_data.fields, field):
                existing = form_data.fields[field]
                if not isinstance(existing, list):
                    form_data.fields[field] = [existing]
                form_data.fields[field].append(value)
            else:
                form_data.fields[field] = value

        # -- files --
        def make_entry(storage):
            raw = storage.read()

            def get_content():
                if encoding in ("binary", "latin-1", None):
                    return raw
                try:
                    return raw.decode(encoding or "utf8")
                except (UnicodeDecodeError, LookupError):
                    return raw

            return Obj({
                "file": Obj({
                    "filename": storage.filename,
                    "mimetype": storage.mimetype,
                    "size": len(raw),
                }),
                "get_content": get_content,
                "getContent": get_content,
            })

        for field in request.files.keys():
            entries = [make_entry(storage) for storage in request.files.getlist(field)]
            form_data.files[field] = entries[0] if len(entries) == 1 else entries

        # formidable can emit 'end' more than once, hence .once in the original.
        return elmer.type.fn.run(elmer.type.fn.once(on_complete), {"args": [form_data]})

    # ----------------------------------------------
    # services.web.register / apiUp
    # ----------------------------------------------
    def register():
        """Announce this API to the base Elmer instance."""
        config = elmer.app.config
        return elmer.io.net.get(
            "http://%s.%s:%s/?register=true"
            % (config.name, config.hostname, config.port)
        )

    def api_up(api_name):
        """Check that each named API's heartbeat endpoint is alive."""
        names = elmer.type.arr.mk(api_name, [api_name])
        result = Obj({"ok": True, "responses": []})

        for name in names:
            response = elmer.io.net.get(
                "http://%s.%s:%s/"
                % (name, elmer.app.config.hostname, elmer.app.config.port)
            )
            result.responses.append(response)

            data = elmer.resolve(response, "data")
            result.ok = bool(
                result.ok
                and response
                and data
                and response.ok
                and elmer.type.str.is_(elmer.resolve(data, "message"), True)
                and elmer.type.date.is_(elmer.resolve(data, "time"))
            )

        return result

    # ----------------------------------------------
    # services.web.router
    # ----------------------------------------------
    class RouterService:
        """Callable router factory that also carries register/registered.

        Mirrors the JS pattern of extending a function with properties.
        """

        def __init__(self):
            self.registered_routes = []

        def __call__(self):
            return Router(server)

        def register(self, route, router, config=None):
            """Mount a router at ``/route``, applying any configured security."""
            elmer_config = elmer.extend(Obj(), getattr(router, "elmer", None), config)

            route_exists = False
            existing = None

            if elmer.type.str.is_(route):
                existing = elmer.type.query(
                    self.registered_routes, {"route": route},
                    {"firstEntryOnly": True, "caseInsensitive": True},
                )
                route_exists = elmer.type.obj.is_(existing, True)

                if not route_exists:
                    mode = elmer.resolve(elmer_config, "security.mode")
                    secure = elmer.type.str.cmp(mode, ["basic", "jwt"])

                    if secure:
                        normalised = mode.strip().lower()
                        if normalised == "basic":
                            from .middleware import _basicauth
                            server.use("/" + route,
                                       _basicauth.apply(elmer, elmer_config.security))
                        elif normalised == "jwt":
                            from .middleware import _jwt
                            server.use("/" + route,
                                       _jwt.apply(elmer, elmer_config.security))

                    server.use("/" + route, router)
                    existing = Obj({
                        "route": route,
                        "secure": secure,
                        "config": elmer_config,
                        "router": router,
                    })
                    self.registered_routes.append(existing)

            return elmer.extend(Obj({"created": not route_exists}), existing)

        def registered(self, route, secure=None):
            """Report whether a route is registered (optionally at a security level)."""
            route_exists = False
            existing = None

            if elmer.type.str.is_(route):
                existing = elmer.type.query(
                    self.registered_routes, {"route": route},
                    {"firstEntryOnly": True, "caseInsensitive": True},
                )
                route_exists = elmer.type.obj.is_(existing, True)

            if not route_exists:
                return False
            if secure is None:
                return True
            return elmer.type.bool.mk(secure, False) == existing.secure

    # ----------------------------------------------
    # services.fs
    # ----------------------------------------------
    def zip_files(files):
        """Build a zip archive from a list of file descriptors.

        Entries may be ``{filename, file}`` objects, arbitrary objects (written
        as JSON) or scalars (written as text) — matching the JSZip original.
        """
        if not elmer.type.arr.is_(files, True):
            return None

        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as archive:
            for index, current in enumerate(files):
                position = index + 1
                if elmer.type.obj.is_(current):
                    if current.get("file") is not None:
                        name = current.get("filename") or "untitled%d.file" % position
                        content = current["file"]
                        archive.writestr(
                            name,
                            content if isinstance(content, (bytes, bytearray))
                            else str(content),
                        )
                    else:
                        import json as _json
                        archive.writestr("untitled%d.json" % position,
                                         _json.dumps(current))
                else:
                    archive.writestr("untitled%d.txt" % position,
                                     elmer.type.str.mk(current))

        payload = buffer.getvalue()

        def http_response(response, save_as_filename=None, http_code=None):
            """Write the archive out as a file download."""
            response.write_head(elmer.type.int.mk(http_code, 200), {
                "Content-Type": "application/zip",
                "Content-disposition":
                    "attachment;filename=" + elmer.type.str.mk(save_as_filename,
                                                               "download.zip"),
                "Content-Length": str(len(payload)),
            })
            response.end(payload)

        return Obj({
            "buffer": payload,
            "http_response": http_response,
            "httpResponse": http_response,
        })

    def require_dir(directory, exclude_files=None, callback=None):
        """Recursively import every module in a directory and hand it to callback.

        This is the mechanism by which ``app/routes/*.py`` are auto-registered.
        """
        elmer.app.status.routes = []

        directory = elmer.type.str.mk(directory)
        directory = ("/" if not directory.startswith("/") else "") + directory
        exclude_files = elmer.type.arr.mk(exclude_files, [])

        if not callable(callback):
            def callback(module, _fs):  # noqa: F811 - default mirrors the original
                module.apply(elmer)

        def recurse(path, relative):
            for entry in sorted(os.listdir(path)):
                full_path = os.path.join(path, entry)
                fs_info = Obj({
                    "file": entry,
                    "dir": path + "/",
                    "path": full_path,
                    "url": (relative.replace("/routes", "", 1)
                            + os.path.splitext(entry)[0]),
                })

                if os.path.isdir(full_path):
                    if entry != "__pycache__":
                        recurse(full_path, entry + "/")
                elif (entry.endswith(".py")
                      and entry not in exclude_files
                      and entry != "__init__.py"):
                    callback(_load_module_from_path(full_path), fs_info)
                    elmer.app.status.routes.append(fs_info)

        recurse(os.path.join(_HERE, directory.lstrip("/")), directory)

    # ----------------------------------------------
    # error.response
    # ----------------------------------------------
    def error_response(response, error_message, http_code=None):
        """Emit a uniform JSON error payload."""
        message = (error_message.get("message")
                   if elmer.type.obj.is_(error_message) else error_message)
        details = elmer.resolve(error_message, "details")

        response.status(elmer.type.int.mk(http_code, 500)).json({
            "success": False,
            "error": message or "An unknown error occurred.",
            "details": details,
        })

    # ----------------------------------------------
    # Assemble $elmer.app
    # ----------------------------------------------
    elmer.app = Obj({
        "version": APP_VERSION,

        "data": Obj(),
        "status": Obj(),
        "config": Obj({
            # Drop the interpreter and script name, leaving only user args.
            "args": sys.argv[1:],
        }),

        "services": Obj({
            "security": Obj(),

            "web": Obj({
                "multipart_form": multipart_form,
                "multipartForm": multipart_form,
                "server": server,
                "ip": Obj({"address": _local_ip}),
                "register": register,
                "router": RouterService(),
                "api_up": api_up,
                "apiUp": api_up,
            }),

            "fs": Obj({
                "base_dir": os.path.join(_HERE, ".."),
                "zip": zip_files,
                "require_dir": require_dir,
                "requireDir": require_dir,
            }),
        }),

        "log": Obj({
            # oData = { status, json, error }
            "api": lambda data, request: None,
        }),

        "error": Obj({
            "response": error_response,
        }),
    })

    return elmer
