"""
##################################################
#
#           ** DO NOT EDIT THIS FILE **
#
##################################################
Express-compatibility layer over Flask.

Elmer is built directly on Express idioms: handlers take ``(oRequest,
oResponse)``, middleware takes ``(oRequest, oResponse, fnContinue)``, routers
are mounted with ``server.use("/prefix", router)``, and responses are written
with ``oResponse.status(200).json({...})``.

Rather than rewrite every route into idiomatic Flask (which would obscure the
correspondence with the original source), this module reproduces those few
Express primitives on top of Flask so the ported application files read as
near line-by-line equivalents of their JavaScript counterparts.

Note on naming: JavaScript's ``oRequest.$trace`` becomes ``oRequest.trace``,
since ``$`` is not a legal identifier character in Python.
"""

import json
import os
import re
from functools import wraps

from flask import Blueprint, Flask
from flask import Response as FlaskResponse
from flask import request as flask_request

from libs.ish.ish import Obj, _wrap

#: Sentinel returned by middleware that handled the request itself.
HANDLED = object()


# ==================================================
# Request
# ==================================================
class Request:
    """Express-shaped view over the current Flask request."""

    def __init__(self, params=None):
        self._flask = flask_request
        self.params = Obj(params or {})
        # Per-request scratch space used by Elmer's middleware.
        self.elmer = Obj()
        self.trace = Obj()
        self.user = None
        self._body_cache = None
        self._querystring_cache = None

    # -- passthroughs -----------------------------------------------
    @property
    def headers(self):
        return Obj({key: value for key, value in self._flask.headers.items()})

    @property
    def cookies(self):
        return Obj(dict(self._flask.cookies))

    @property
    def method(self):
        return self._flask.method

    @property
    def path(self):
        return self._flask.path

    @property
    def url(self):
        """Express's req.url: path plus query string, not the absolute URL."""
        return self._flask.full_path.rstrip("?") or self._flask.path

    @property
    def full_url(self):
        return self._flask.url

    @property
    def files(self):
        return self._flask.files

    @property
    def form(self):
        return self._flask.form

    @property
    def raw(self):
        """Escape hatch to the underlying Flask request."""
        return self._flask

    # -- body -------------------------------------------------------
    @property
    def body(self):
        """Parsed request body, mirroring body-parser's json + urlencoded.

        Returns an empty object rather than None so that ``oRequest.body.data``
        style access degrades the way it does in JavaScript.
        """
        if self._body_cache is not None:
            return self._body_cache

        parsed = None
        content_type = (self._flask.content_type or "").lower()

        if "json" in content_type:
            parsed = self._flask.get_json(silent=True)
        elif "form" in content_type:
            parsed = {key: value for key, value in self._flask.form.items()}
        else:
            # body-parser is often configured with type "*/*" in Elmer, so make
            # a best effort at JSON regardless of the declared content type.
            raw = self._flask.get_data(as_text=True)
            if raw:
                try:
                    parsed = json.loads(raw)
                except (ValueError, TypeError):
                    parsed = None

        self._body_cache = _wrap(parsed) if isinstance(parsed, dict) else Obj()
        return self._body_cache

    # -- query ------------------------------------------------------
    @property
    def querystring(self):
        """Attached by the CORS middleware in app_ex; computed lazily here too."""
        if self._querystring_cache is None:
            result = Obj()
            for key in self._flask.args.keys():
                values = self._flask.args.getlist(key)
                result[key] = values[0] if len(values) == 1 else values
            self._querystring_cache = result
        return self._querystring_cache

    @querystring.setter
    def querystring(self, value):
        self._querystring_cache = _wrap(value)


# ==================================================
# Response
# ==================================================
class Response:
    """Express-shaped response builder.

    Handlers mutate this object; the router adapter then converts it into a
    real Flask response once the handler returns.
    """

    def __init__(self):
        self.status_code = 200
        self.headers = {}
        self.body = None
        self.is_json = False
        self.finished = False
        self._finish_handlers = []
        self.error_code = 0

    # -- Express API ------------------------------------------------
    def status(self, code):
        """Set the status code; chainable, as in Express."""
        self.status_code = int(code) if code is not None else 200
        return self

    def json(self, payload=None):
        """Send a JSON body and mark the response complete."""
        self.body = payload
        self.is_json = True
        self.finished = True
        return self

    def send(self, payload=None):
        self.body = payload
        self.is_json = isinstance(payload, (dict, list))
        self.finished = True
        return self

    def set(self, name, value):
        """Set a response header; chainable."""
        self.headers[name] = value if isinstance(value, str) else str(value)
        return self

    setHeader = set

    def write_head(self, status_code, headers=None):
        """Node's res.writeHead; used by the zip helper."""
        self.status(status_code)
        for name, value in (headers or {}).items():
            self.set(name, value)
        return self

    writeHead = write_head

    def end(self, payload=None):
        if payload is not None:
            self.body = payload
            self.is_json = False
        self.finished = True
        return self

    def on(self, event, handler):
        """Register an event handler. Only 'finish' is meaningful here."""
        if event == "finish" and callable(handler):
            self._finish_handlers.append(handler)
        return self

    def error_code_set(self, error):
        """Equivalent of Express's monkeypatched res.$errorCode."""
        self.error_code = error
        return self

    # -- adapter ----------------------------------------------------
    def emit_finish(self):
        """Fire the 'finish' listeners (logging/caching middleware hook here)."""
        for handler in self._finish_handlers:
            try:
                handler()
            except Exception as error:  # a logging failure must not 500 the request
                print("Error in finish handler: %s" % error)

    def to_flask(self):
        """Materialise a Flask response from the accumulated state."""
        if self.is_json:
            payload = json.dumps(self.body, default=str)
            response = FlaskResponse(payload, status=self.status_code,
                                     mimetype="application/json")
        elif isinstance(self.body, (bytes, bytearray)):
            response = FlaskResponse(bytes(self.body), status=self.status_code,
                                     mimetype="application/octet-stream")
        else:
            body = "" if self.body is None else str(self.body)
            response = FlaskResponse(body, status=self.status_code)

        for name, value in self.headers.items():
            response.headers[name] = value
        return response


# ==================================================
# Middleware execution
# ==================================================
def run_middleware(stack, request, response):
    """Run an Express-style middleware chain.

    Each entry is called as ``fn(request, response, fnContinue)``. A middleware
    that never invokes ``fnContinue`` (or that writes a response) short-circuits
    the chain, exactly as in Express. Returns True when the chain completed and
    the route handler should run.
    """
    for middleware in stack:
        state = {"continued": False}

        def fn_continue(*_args, **_kwargs):
            state["continued"] = True

        middleware(request, response, fn_continue)

        if not state["continued"]:
            return False
        if response.finished:
            return False
    return True


# ==================================================
# Router
# ==================================================
class Router:
    """Express Router equivalent, backed by a Flask Blueprint."""

    _counter = 0

    def __init__(self, server=None, name=None):
        Router._counter += 1
        self.name = name or ("router_%d" % Router._counter)
        self.server = server
        self.elmer = Obj()
        self.middleware = []
        self.routes = []
        self._blueprint = None

    # -- registration -----------------------------------------------
    def use(self, handler):
        """Add router-level middleware."""
        self.middleware.append(handler)
        return self

    def _add(self, methods, rule, handler):
        self.routes.append({
            "methods": methods,
            "rule": rule,
            "handler": handler,
        })
        return handler

    def get(self, rule):
        def decorator(handler):
            return self._add(["GET"], rule, handler)
        return decorator

    def post(self, rule):
        def decorator(handler):
            return self._add(["POST"], rule, handler)
        return decorator

    def put(self, rule):
        def decorator(handler):
            return self._add(["PUT"], rule, handler)
        return decorator

    def delete(self, rule):
        def decorator(handler):
            return self._add(["DELETE"], rule, handler)
        return decorator

    def all(self, rule):
        def decorator(handler):
            return self._add(
                ["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS"],
                rule, handler,
            )
        return decorator

    # -- conversion --------------------------------------------------
    @staticmethod
    def _to_flask_rule(rule):
        """Convert an Express path to a Flask rule.

        ``/response/:id`` becomes ``/response/<id>``; a trailing ``*`` becomes a
        catch-all path converter.
        """
        rule = rule or "/"
        if not rule.startswith("/"):
            rule = "/" + rule
        rule = re.sub(r":([A-Za-z_][A-Za-z0-9_]*)", r"<\1>", rule)
        if rule.endswith("*"):
            rule = rule[:-1].rstrip("/") + "/<path:wildcard>"
        return rule

    def build_blueprint(self, prefix, server_middleware_for):
        """Create the Flask Blueprint that serves this router's routes."""
        prefix = "/" + (prefix or "").strip("/")
        blueprint_name = "%s_%s" % (self.name, abs(hash(prefix)) % 100000)
        blueprint = Blueprint(blueprint_name, __name__)

        for index, route in enumerate(self.routes):
            flask_rule = self._to_flask_rule(route["rule"])
            handler = route["handler"]

            def make_view(handler=handler):
                @wraps(handler)
                def view(**params):
                    request = Request(params)
                    response = Response()

                    # Server-level middleware registered for this mount point,
                    # then router-level middleware, then the handler itself.
                    stack = list(server_middleware_for(request.path))
                    stack.extend(self.middleware)

                    if run_middleware(stack, request, response):
                        handler(request, response)

                    response.emit_finish()
                    return response.to_flask()
                return view

            endpoint = "%s_%d" % (blueprint_name, index)
            blueprint.add_url_rule(
                flask_rule,
                endpoint=endpoint,
                view_func=make_view(),
                methods=route["methods"],
                strict_slashes=False,
            )

            # Express treats "/foo" and "/foo/" alike; register the bare prefix
            # too so a router mounted at "/x" answers GET /x as well as GET /x/.
            #     NOTE: skipped at the root, where the bare rule would be "".
            if flask_rule == "/" and prefix != "/":
                blueprint.add_url_rule(
                    "",
                    endpoint=endpoint + "_bare",
                    view_func=make_view(),
                    methods=route["methods"],
                    strict_slashes=False,
                )

        self._blueprint = blueprint
        return blueprint


# ==================================================
# Server
# ==================================================
class Server:
    """Express application equivalent, backed by a Flask app."""

    def __init__(self, static_folder=None, import_name="elmer"):
        self.flask = Flask(import_name, static_folder=None)
        self.middleware = []          # list of (prefix, handler)
        self.mounted = []             # bookkeeping for registered routers
        self._static_mounts = []
        # Routers mounted after the first request is served (see mount()).
        self._dynamic = []
        self._catchall_installed = False

    # -- Express API -------------------------------------------------
    def use(self, path_or_handler, handler=None):
        """Mount middleware, a Router, or a static directory.

        Supports both Express call shapes: ``use(fn)`` and ``use(path, fn)``.
        """
        if handler is None:
            path, target = "/", path_or_handler
        else:
            path, target = path_or_handler or "/", handler

        if isinstance(target, Router):
            self.mount(path, target)
        elif callable(target):
            self.middleware.append((self._normalise(path), target))
        return self

    @staticmethod
    def _normalise(path):
        path = "/" + (path or "").strip("/")
        return path

    def middleware_for(self, path):
        """Return the middleware stack applicable to a request path."""
        applicable = []
        for prefix, handler in self.middleware:
            if prefix == "/" or path == prefix or path.startswith(prefix + "/"):
                applicable.append(handler)
        return applicable

    def mount(self, prefix, router):
        """Register a Router at the given URL prefix.

        Express lets you mount routers at any time; Flask freezes its URL map
        once the first request is served. Elmer needs runtime mounting for
        ``/elmer/proxy`` (child APIs register themselves while the server is
        already running), so routers added after startup are dispatched by the
        catch-all installed in :meth:`install_catchall` instead.
        """
        normalised = self._normalise(prefix)

        # Flask renamed this attribute across versions; check both.
        started = getattr(self.flask, "got_first_request",
                          getattr(self.flask, "_got_first_request", False))
        if started:
            return self._mount_dynamic(normalised, router)

        blueprint = router.build_blueprint(normalised, self.middleware_for)
        url_prefix = None if normalised == "/" else normalised
        self.flask.register_blueprint(blueprint, url_prefix=url_prefix)
        self.mounted.append({"prefix": normalised, "router": router})
        return self

    def _mount_dynamic(self, prefix, router):
        """Register a router into the runtime (post-startup) dispatch table."""
        from werkzeug.routing import Map, Rule

        rules, handlers = [], {}
        for index, route in enumerate(router.routes):
            endpoint = "dyn_%d_%d" % (len(self._dynamic), index)
            rules.append(Rule(
                Router._to_flask_rule(route["rule"]),
                endpoint=endpoint,
                methods=route["methods"],
            ))
            handlers[endpoint] = route["handler"]

        # Replace any existing mount at this prefix (a re-registering child API).
        self._dynamic = [e for e in self._dynamic if e["prefix"] != prefix]
        self._dynamic.append({
            "prefix": prefix,
            "router": router,
            "map": Map(rules, strict_slashes=False),
            "handlers": handlers,
        })
        self.mounted.append({"prefix": prefix, "router": router})
        return self

    def install_catchall(self):
        """Install the fallback route that serves dynamically mounted routers.

        Registered once, before the first request. Werkzeug ranks rules using a
        path converter below concrete rules, so this only runs when nothing
        statically registered matches.
        """
        if self._catchall_installed:
            return self

        from werkzeug.exceptions import MethodNotAllowed, NotFound

        def dynamic_view(dynamic_path=""):
            path = "/" + dynamic_path.strip("/")

            # Longest prefix wins, so "/a/b" beats "/a".
            for entry in sorted(self._dynamic,
                                key=lambda e: -len(e["prefix"])):
                prefix = entry["prefix"]
                if prefix != "/" and not (path == prefix
                                          or path.startswith(prefix + "/")):
                    continue

                remainder = path[len(prefix):] if prefix != "/" else path
                remainder = remainder or "/"

                adapter = entry["map"].bind("localhost", path_info=remainder)
                try:
                    endpoint, params = adapter.match(method=flask_request.method)
                except (NotFound, MethodNotAllowed):
                    continue

                request = Request(params)
                response = Response()

                stack = list(self.middleware_for(path))
                stack.extend(entry["router"].middleware)

                if run_middleware(stack, request, response):
                    entry["handlers"][endpoint](request, response)

                response.emit_finish()
                return response.to_flask()

            return FlaskResponse(
                json.dumps({"error": "Not Found", "path": path}),
                status=404, mimetype="application/json",
            )

        self.flask.add_url_rule(
            "/<path:dynamic_path>",
            endpoint="elmer_dynamic_dispatch",
            view_func=dynamic_view,
            methods=["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS"],
        )
        self._catchall_installed = True
        return self

    def static(self, url_prefix, directory):
        """Serve a directory of static files (express.static equivalent)."""
        from flask import send_from_directory

        url_prefix = self._normalise(url_prefix)
        endpoint = "static_%s" % re.sub(r"[^a-zA-Z0-9]", "_", url_prefix)

        def view(filename=""):
            # Express's static middleware serves a directory's index.html when
            # the path names a directory; mirror that so routes like
            # /www/managetickets/status resolve to .../status/index.html.
            target = filename or "index.html"
            if os.path.isdir(os.path.join(directory, target)):
                target = target.rstrip("/") + "/index.html"
            return send_from_directory(directory, target)

        self.flask.add_url_rule(
            url_prefix + "/", endpoint=endpoint, view_func=view, methods=["GET"]
        )
        self.flask.add_url_rule(
            url_prefix + "/<path:filename>",
            endpoint=endpoint + "_file", view_func=view, methods=["GET"],
        )
        self._static_mounts.append((url_prefix, directory))
        return self

    def listen(self, port, host="0.0.0.0", callback=None, debug=False):
        """Start the server, invoking callback once routes are configured."""
        if callable(callback):
            callback()
        self.flask.run(host=host, port=int(port), debug=debug, threaded=True)
