"""
##################################################
#
#           ** DO NOT EDIT THIS FILE **
#
##################################################
Version: 0.1.2025-03-27 (Python port of app/app-ex.js)

The "base Elmer" extensions: a CORS-aware router factory, and a router
registry that can mount either a local router or a reverse proxy to a
registered child API.
"""

import requests
from flask import Response as FlaskResponse
from flask import request as flask_request

from libs.ish.ish import Obj

from ._express import Router

APP_VERSION_EX = "0.1.2025-03-27"

#: Hop-by-hop headers that must not be forwarded through the proxy.
_HOP_BY_HOP = {
    "connection", "keep-alive", "proxy-authenticate", "proxy-authorization",
    "te", "trailers", "transfer-encoding", "upgrade", "content-encoding",
    "content-length",
}


def _make_proxy_router(elmer, target_url):
    """Build a catch-all Router that reverse-proxies to target_url.

    Equivalent to ``express-http-proxy`` with ``parseReqBody: false`` — the
    body is streamed through untouched so that uploads survive the hop.
    """
    router = Router()

    def forward(request, response, wildcard=""):
        suffix = request.raw.full_path.rstrip("?")
        url = target_url.rstrip("/") + "/" + suffix.lstrip("/")

        headers = {
            key: value for key, value in request.headers.items()
            if key.lower() not in _HOP_BY_HOP
        }

        try:
            upstream = requests.request(
                method=request.method,
                url=url,
                headers=headers,
                data=flask_request.get_data(),
                params=None,
                allow_redirects=False,
                timeout=60,
            )
        except requests.RequestException as error:
            response.status(502).json({
                "error": "Bad gateway",
                "target": url,
                "details": str(error),
            })
            return

        response.status(upstream.status_code)
        for key, value in upstream.headers.items():
            if key.lower() not in _HOP_BY_HOP:
                response.set(key, value)
        response.end(upstream.content)

    # A single catch-all covering the mount point and everything beneath it.
    router.all("/")(lambda req, res: forward(req, res))
    router.all("/*")(lambda req, res, **kwargs: forward(req, res))
    return router


def apply(elmer):
    """Extend ``elmer.app``. Equivalent to ``require('./app/app-ex.js')(...)``."""
    elmer.app.versionEx = APP_VERSION_EX

    server = elmer.app.services.web.server
    original_registered = elmer.app.services.web.router.registered

    # ----------------------------------------------
    # services.web.configBodyParser
    # ----------------------------------------------
    def config_body_parser(route=None):
        """Configure request body limits.

        Express needed explicit body-parser wiring (and needed it *excluded*
        from proxied routes, since parsing consumes the stream). Flask parses
        bodies lazily on access, so the proxy problem does not arise; all that
        remains is enforcing the configured upload ceiling.
        """
        limit_mb = elmer.type.int.mk(
            elmer.resolve(elmer.app.config, "uploadLimitMb"), 500
        )
        server.flask.config["MAX_CONTENT_LENGTH"] = limit_mb * 1024 * 1024
        return route

    # ----------------------------------------------
    # services.web.router (overloads the base version)
    # ----------------------------------------------
    class RouterServiceEx:
        """Router factory + registry with CORS and proxy support."""

        def __init__(self):
            self.registered_routes = []
            self.registered = original_registered

        def __call__(self):
            """Create a router preconfigured with the CORS middleware."""
            router = Router(server)

            def cors(request, response, fn_continue):
                origin = request.headers.get("Origin") or request.headers.get("origin")

                # Only echo back origins we explicitly trust.
                whitelist = elmer.resolve(
                    elmer.app.config, "security.corsWhitelist", []
                ) or []
                if origin and origin in whitelist:
                    response.set("Access-Control-Allow-Origin", origin)

                # NOTE: CRUD = POST, GET/POST, PUT, DELETE
                response.set("Access-Control-Allow-Methods", "GET,POST,PUT,DELETE")
                response.set(
                    "Access-Control-Allow-Headers",
                    "X-Requested-With,content-type,Authorization",
                )
                response.set("Access-Control-Allow-Credentials", "true")

                # Parse the querystring and attach it to the request.
                request.querystring = elmer.io.web.queryString.parse(request.url)

                fn_continue()

            router.use(cors)
            return router

        def register(self, route, router_or_url, config=None):
            """Mount a local router, or a proxy to ``host:port``, at ``/route``."""
            proxy_url = None
            router = None
            remove_prefix_from_path = elmer.type.str.mk(route)

            if elmer.type.str.is_(router_or_url):
                proxy_url = elmer.type.str.mk(router_or_url)
                config = elmer.type.obj.mk(config, Obj())
            else:
                router = router_or_url
                config = elmer.extend(Obj(), getattr(router, "elmer", None), config)

            remove_prefix = remove_prefix_from_path != ""
            if remove_prefix:
                remove_prefix_from_path = (
                    ("" if remove_prefix_from_path.startswith("/") else "/")
                    + remove_prefix_from_path
                )

            secure = (
                elmer.type.obj.is_(config.get("security"), True)
                and elmer.type.str.is_(elmer.resolve(config, "security.mode"), True)
            )

            route_exists = False
            existing = None

            if elmer.type.str.is_(route):
                existing = elmer.type.query(
                    self.registered_routes, {"route": route},
                    {"firstEntryOnly": True, "caseInsensitive": True},
                )
                route_exists = elmer.type.obj.is_(existing, True)

                if not route_exists:
                    if secure:
                        mode = config.security.mode.strip().lower()
                        if mode == "basic":
                            from .middleware import _basicauth
                            server.use("/" + route,
                                       _basicauth.apply(elmer, config.security))
                        elif mode == "jwt":
                            from .middleware import _jwt
                            server.use("/" + route,
                                       _jwt.apply(elmer, config.security))
                        # TODO: oauth? api key?

                    if proxy_url:
                        url = "http://" + proxy_url
                        if remove_prefix:
                            url = url.replace(remove_prefix_from_path, "")
                        router = _make_proxy_router(elmer, url)

                    from .middleware import _cache
                    server.use("/" + route, _cache.apply(elmer, route))
                    server.use("/" + route, router)

                    existing = Obj({
                        "route": route,
                        "secure": secure,
                        "config": config,
                        "router": router,
                    })
                    self.registered_routes.append(existing)

            return elmer.extend(
                Obj({
                    "created": not route_exists,
                    "securityMismatch": (
                        existing.secure != secure
                        if elmer.type.obj.is_(existing) else False
                    ),
                }),
                existing,
            )

    # ----------------------------------------------
    # Extend the app namespace
    # ----------------------------------------------
    elmer.app.cache = Obj()
    elmer.app.enums = Obj({
        "userTypes": Obj({
            "admin": 0,
            "internal": 1,
            "external": 2,
        })
    })

    elmer.app.services.web.config_body_parser = config_body_parser
    elmer.app.services.web.configBodyParser = config_body_parser
    elmer.app.services.web.router = RouterServiceEx()

    return elmer
