"""
##################################################
#
#           ** DO NOT EDIT THIS FILE **
#
##################################################
Version: 2023-04-08 (Python port of app/routes/_routes.js)

Sets up the root/heartbeat route, the /login route (base Elmer only), then
auto-discovers and registers every other module under app/routes.
"""

from datetime import datetime


def apply(elmer):
    """Configure all application routes."""
    base_router = elmer.app.services.web.router()

    # Setup the root/heartbeat route
    # curl -X GET http://localhost:3000/
    @base_router.get("/")
    def _root(request, response):
        querystring = elmer.io.web.queryString.parse(request.url)

        # If this is a .register call
        if elmer.type.bool.mk(querystring.get("register"), False):
            config = elmer.app.config

            if elmer.type.bool.mk(config.get("baseElmer"), False):
                server_name = "%s.%s" % (config.name, config.hostname)
            else:
                # See: https://www.abstractapi.com/guides/node-js-get-ip-address
                server_name = elmer.app.services.web.ip.address()

            api_response = elmer.io.net.post(
                "http://%s.%s:%s/elmer/proxy/"
                % (config.net, config.hostname, config.port),
                {
                    "route": config.name,
                    "port": config.port,
                    "force": elmer.type.bool.mk(config.get("forceRegister"), True),
                    "server": server_name,
                    "config": elmer.type.obj.mk(request.elmer, {}),
                },
            )

            response.status(api_response.status).json({
                "registered": api_response.ok,
                "api": api_response,
            })

        # Else this is a heartbeat call
        else:
            now = datetime.now()
            response.status(200).json({
                "ok": True,
                "message": "Hi \U0001F44B from " + elmer.type.str.mk(
                    elmer.app.config.get("name")
                ),
                "time": now.isoformat(),
                "localTime": elmer.type.date.format(now, "YYYY-MM-DD HH:mm:ss"),
                "versions": {
                    "ish": elmer.config.ish().ver,
                    "app": elmer.app.version,
                    "appEx": elmer.app.versionEx,
                },
            })

    # Register the base router, then — if this is base Elmer — the /login route.
    elmer.app.services.web.router.register("", base_router)

    if elmer.type.bool.mk(elmer.app.config.get("baseElmer"), False):
        from ..middleware import _jwt
        _jwt.apply(elmer, None)
        elmer.app.services.web.router.register(
            "login", elmer.app.services.security.jwt.login_router()
        )

    # Auto-register every other module under /routes.
    def on_route_file(module, fs_info):
        file_router = elmer.app.services.web.router()

        # Pass the freshly created router along with the base router, mirroring
        # the JS signature module(elmer, router, baseRouter).
        returned = module.apply(elmer, file_router, base_router)

        # So long as the module didn't return False, register the route.
        if returned is not False:
            file_router = returned or file_router
            elmer.app.services.web.router.register(fs_info.url, file_router)

    elmer.app.services.fs.require_dir("routes", ["_routes.py"], on_route_file)
