"""
##################################################
#
#           ** DO NOT EDIT THIS FILE **
#
##################################################
Version: 2025-03-27 (Python port of app/routes/elmer.js)

The base Elmer route set:
  * /elmer/proxy        — child API registration
  * /elmer/response/*   — long-running response tracking
  * /elmer/cache/*      — inspection and clearing of the response cache
"""

from libs.ish.ish import Obj


def apply(elmer, router, base_router=None):
    """Define the Elmer routes on the passed router."""

    # Setup the required app.data.proxy variables
    elmer.app.data.proxy = []
    elmer.app.data.proxy_disallowed = ["", "login", "elmer"]

    elmer.app.data.response = Obj()

    # ----------------------------------------------
    # /elmer/proxy — allows the registration of child APIs
    # ----------------------------------------------
    @router.post("/proxy")
    def _proxy(request, response):
        body = elmer.type.obj.mk(request.body, Obj())
        route_name = elmer.type.str.mk(body.get("route")).lower()
        route = elmer.type.query(
            elmer.app.data.proxy, {"route": route_name}, {"firstEntryOnly": True}
        )
        config = elmer.type.obj.mk(body.get("config"), Obj())
        secure = (
            elmer.type.obj.is_(config.get("security"), True)
            and elmer.type.str.is_(elmer.resolve(config, "security.mode"), True)
        )
        success = False

        # If an existing route was found above
        if elmer.type.obj.is_(route):
            # If we are to force registration over it, reset its values.
            if elmer.type.bool.mk(body.get("force"), False):
                success = True
                route.secure = secure
                route.config = config
                route.server = body.get("server")
                route.port = body.get("port")
                route.instance = elmer.type.int.mk(route.get("instance"), 0) + 1

        # Else if the route name isn't disallowed, set up a new route.
        elif route_name not in elmer.app.data.proxy_disallowed:
            success = True
            route = Obj({
                "route": route_name,
                "secure": secure,
                "config": config,
                "server": body.get("server"),
                "port": body.get("port"),
                "instance": 1,
                "id": elmer.type.uuid(),
            })
            elmer.app.data.proxy.append(route)

        # If the route was successfully set above, register it.
        if success:
            route = elmer.extend(
                route,
                elmer.app.services.web.router.register(
                    route_name,
                    "%s:%s" % (route.get("server"), route.get("port")),
                    config,
                ),
            )

            # If this proxy route is secure, register its login router too.
            if secure:
                mode = config.security.mode.strip().lower()
                login_router = elmer.resolve(
                    elmer.app.services.security, mode + ".login_router"
                )

                if elmer.type.fn.is_(login_router):
                    elmer.app.services.web.router.register(
                        route_name + "/login", login_router()
                    )

        status = (elmer.io.net.status.success.ok if success
                  else elmer.io.net.status.clientError.conflict)
        response.status(status).json(route)

    # ----------------------------------------------
    # /elmer/response — create a tracked response
    # ----------------------------------------------
    @router.post("/response")
    def _response_create(request, response):
        start = elmer.type.date.timestamp()

        # Ensure that we generate a new, unused id.
        while True:
            response_id = elmer.type.uuid()
            if response_id not in elmer.app.data.response:
                break

        elmer.app.data.response[response_id] = Obj({
            "data": elmer.resolve(request.body, "data"),
            "start": start,
            "updated": start,
            "done": (elmer.type.date.ydhms(start)
                     if elmer.resolve(request.body, "done") is True else ""),
            "cancel": False,
            "cancelled": False,
        })

        response.status(200).json({
            "ok": True,
            "id": response_id,
            "cancel": False,
        })

    # ----------------------------------------------
    # /elmer/response/:id — update a tracked response
    # ----------------------------------------------
    @router.post("/response/:id")
    def _response_update(request, response):
        response_id = request.params.get("id")
        ok = response_id in elmer.app.data.response
        now = elmer.type.date.timestamp()

        if ok:
            entry = elmer.app.data.response[response_id]
            elmer.extend(entry, Obj({
                "data": elmer.resolve(request.body, "data"),
                "updated": now,
                "done": (elmer.type.date.ydhms(entry.get("start"), now)
                         if elmer.resolve(request.body, "done") is True else ""),
                "cancelled": elmer.resolve(request.body, "cancelled") is True,
            }))

        payload = elmer.extend(
            Obj(), elmer.app.data.response.get(response_id, Obj()),
            Obj({"ok": ok, "id": response_id}),
        )
        response.status(200 if ok else 404).json(payload)

    # ----------------------------------------------
    # /elmer/response/:id — read a tracked response
    # ----------------------------------------------
    @router.get("/response/:id")
    def _response_read(request, response):
        response_id = request.params.get("id")
        ok = response_id in elmer.app.data.response

        payload = elmer.extend(
            Obj(), elmer.app.data.response.get(response_id, Obj()),
            Obj({"ok": ok, "id": response_id}),
        )
        response.status(200 if ok else 404).json(payload)

        if ok and elmer.type.bool.mk(request.querystring.get("delete"), False):
            del elmer.app.data.response[response_id]
        elif ok and elmer.type.bool.mk(request.querystring.get("cancel"), False):
            elmer.app.data.response[response_id]["cancel"] = True

    # ----------------------------------------------
    # /elmer/cache/id/:id
    # ----------------------------------------------
    @router.get("/cache/id/:id")
    def _cache_by_id(request, response):
        cache_id = request.params.get("id")
        data = elmer.type.query(elmer.app.cache, {"trace": {"id": cache_id}})
        status = 200 if elmer.type.arr.is_(data, True) else 404

        response.status(status).json({"id": cache_id, "data": data})

    # ----------------------------------------------
    # /elmer/cache/clear/id/:id
    # ----------------------------------------------
    @router.get("/cache/clear/id/:id")
    def _cache_clear_by_id(request, response):
        cache_id = request.params.get("id")
        cleared = cache_id in elmer.app.cache
        status = 200 if cleared else 404

        if cleared:
            del elmer.app.cache[cache_id]

        response.status(status).json({"id": cache_id, "cleared": cleared})

    # ----------------------------------------------
    # /elmer/cache/route/:route
    # ----------------------------------------------
    @router.get("/cache/route/:route")
    def _cache_by_route(request, response):
        route = request.params.get("route")
        data = elmer.type.query(elmer.app.cache, {"route": route})
        status = 200 if elmer.type.arr.is_(data, True) else 404

        response.status(status).json({"route": route, "data": data})

    # ----------------------------------------------
    # /elmer/cache/route/:route/:subroute
    # ----------------------------------------------
    @router.get("/cache/route/:route/:subroute")
    def _cache_by_subroute(request, response):
        route = request.params.get("route")
        subroute = request.params.get("subroute")
        data = elmer.type.query(
            elmer.app.cache, {"route": route, "subroute": subroute}
        )
        status = 200 if elmer.type.arr.is_(data, True) else 404

        response.status(status).json({
            "route": route,
            "subroute": subroute,
            "data": data,
        })

    # ----------------------------------------------
    # /elmer/cache/clear/route/:route
    # ----------------------------------------------
    @router.get("/cache/clear/route/:route")
    def _cache_clear_by_route(request, response):
        route = request.params.get("route")
        data = elmer.type.query(elmer.app.cache, {"route": route})
        status = 200 if elmer.type.arr.is_(data, True) else 404

        if status == 200:
            for entry in data:
                elmer.app.cache.pop(elmer.resolve(entry, "trace.id"), None)

        response.status(status).json({
            "route": route,
            "cleared": status == 200,
        })

    # ----------------------------------------------
    # /elmer/cache/clear/route/:route/:subroute
    # ----------------------------------------------
    @router.get("/cache/clear/route/:route/:subroute")
    def _cache_clear_by_subroute(request, response):
        route = request.params.get("route")
        subroute = request.params.get("subroute")
        data = elmer.type.query(
            elmer.app.cache, {"route": route, "subroute": subroute}
        )
        status = 200 if elmer.type.arr.is_(data, True) else 404

        if status == 200:
            for entry in data:
                elmer.app.cache.pop(elmer.resolve(entry, "trace.id"), None)

        response.status(status).json({
            "route": route,
            "cleared": status == 200,
        })

    # ----------------------------------------------
    # /elmer/cache/clear/before/:before
    # ----------------------------------------------
    @router.get("/cache/clear/before/:before")
    def _cache_clear_before(request, response):
        before = elmer.type.date.mk(request.params.get("before"), None)
        cleared_count = 0

        if before is not None:
            for cache_id in list(elmer.app.cache.keys()):
                entries = elmer.app.cache.get(cache_id) or []
                kept = [
                    entry for entry in entries
                    if not (
                        elmer.type.date.mk(elmer.resolve(entry, "trace.when"), None)
                        and elmer.type.date.cmp(
                            elmer.type.date.mk(
                                elmer.resolve(entry, "trace.when"), None
                            ),
                            before,
                        ) < 0
                    )
                ]
                cleared_count += len(entries) - len(kept)
                if kept:
                    elmer.app.cache[cache_id] = kept
                else:
                    del elmer.app.cache[cache_id]

        status = 200 if before is not None else 404
        response.status(status).json({
            "before": request.params.get("before"),
            "cleared": status == 200,
            "count": cleared_count,
        })
